### ISSUE TITLE
ML algorithm to show forecasts

### ISSUE THREAD

**Issue by hangong** [isjeffcom/coronvirusFigureUK#1]
It would be interesting to add a feature of forecast for the next 7 days based on the existing data.

For example, this can be done by using a 3-degree poly model or exponential model.

If the 3-degree poly model is correct, we shall see 80 new cases on 9th March.
If the exponential model is correct, we shall see 95 new cases on 9th March.

Good work!

**Comment by isjeffcom** [comment]
Good idea! A forecast index is good for alerting people what is going to coming, however, we need to think of if these going panic people. Looking forward to your work!

**Comment by hangong** [comment]
Well said.. Maybe it is better not to add it.. Perhaps only make it available as a CLI tool so only geeks can access.. XD
