### ISSUE TITLE
Change render output

### ISSUE THREAD

**Issue by lkd70** [isjeffcom/coronvirusFigureUK#6]
Data should be output with res.json instead of res.text where JSON data is returned. This will allow clients to better parse the data

**Comment by isjeffcom** [comment]
Thank you for notifying me. I didn't saw any different from res.send and res.json as send will automatically set Content-Type to JSON if the output is a JSON format object which gives more flexibility. I am personally using Axios for HTTP request in the front-end, no problem so far. 

However, I will look into it and see if this will cause any performance issue, or just its not the right thing to do. 

I will close this issue for now as it's not an urgent problem. Cheers
