### ISSUE TITLE
Postman collection for the API

### ISSUE THREAD

**Issue by arlemi** [isjeffcom/coronvirusFigureUK#7]
Hey there 👋 

I've created the following collection to make it easier for interested users to query your API: https://explore.postman.com/templates/6818/uk-coronavirus-data-api

We're gathering a list of APIs around Covid-19 and would love to add yours if you'd allow us, you can check the current list here: https://github.com/postmanlabs/covid-19-apis

Also for now the collection is published under my name but I'm more than happy to give you ownership if you'd prefer!

**Comment by isjeffcom** [comment]
Thank you. I am happy to be listed on.
